routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});



Route::get('history', function () {
    return view('history');
});


Route::get('employee', function () {
    return view('employee');
});

Route::get('home', function () {
    return view('home');
});

Route::get('profile', function () {
    return view('profile');
});

Route::get('eprofile', function () {
    return view('eprofile');
});

Route::get('welcome', function () {
    return view('welcome');
});

Route::get('/employee', 'Account\EmployeeController@show')->name('Employee_View');
Route::get('/employee/delete/{id}', 'Account\EmployeeController@delete')->name('Employee_Destroy');
Route::get('/employee/edit/{id}', 'Account\EmployeeController@edit')->name('Employee_Edit');
Route::post('/employee/edit', 'Account\EmployeeController@editing')->name('Employee_Edit_POST');
Route::get('/employee/add', 'Account\EmployeeController@add')->name('Employee_Add_GET');
Route::post('/employee/add', 'Account\EmployeeController@adding')->name('Employee_Add_POST');



Route::resource('/WorkingHour','WorkingHoursController');

Route::resource('/users','EditController');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/WorkingHour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WorkingHour extends Model
{
    protected $fillable = ['day', 'start_time', 'finish_time', 'id', 'peried', 'periodOut','user_id'];
}

app/Http/Controllers/WorkingHoursController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\WorkingHour;
use Illuminate\Support\Facades\Auth;


class WorkingHoursController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view(' WorkingHour.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view(' WorkingHour.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "start_time" => "required:working_hours",

        ]);

        $request->validate([
            "finish_time" => "required:working_hours",
        ]);
        $request->validate([

            "day" => "required:working_hours",
        ]);


        $request->validate([

            "peried" => "required:working_hours",
        ]);

        $request->validate([

            "periodOut" => "required:working_hours",
        ]);
       // $user_id = Auth::user()->id;

       WorkingHour::create($request->all());

        return view('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/WorkingHour/create.blade.php
@extends('layout')
@section('content')
<html>

<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <style>
    .card-header {
      background-color: #343a40;
      color: #FFFFFF;
      text-align: left;
      font-family: "Times New Roman", Times, serif;
      font-size: 30px;
    }

    .control-label col-4 {
      font-family: "Times New Roman", Times, serif;
    }

    input[type=text] {
      width: 200px;

    }

    #p3 {
      text-align: right;

    }
  </style>
</head>


<body>
  <div class="container">

    <div class="card">
      <div class="card-header">Shift Setup </div>
      <div class="card-body">

        <form action="{{ route('WorkingHour.store') }}" method="POST">
          @csrf
          <input type="hidden" value="{{Auth::user()->id}}" name="user_id"/>
          <label for="days">Working Day:</label>
          <input type="date" class="form-control" name="day">
          <label for="time">Time in:</label>
          <input type="time" class="form-control" name="start_time">
          <label for="time">Time late:</label>
          <input type="number" class="form-control" name="peried">
          <label for="time">Time out:</label>
          <input type="time" class="form-control" name="finish_time">
          <label for="time">Early leaving:</label>
          <input type="number" class="form-control" name="periodOut">
          <button type="submit" class="btn btn-primary float-right"> submit</button>

        </form>
      </div>

    </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>
@endsection